### ISSUE TITLE
Std. jobs from generateconfs in cron

### ISSUE THREAD

**Issue by ARiis-63** [ucphhpc/docker-migrid#23]
standard jobs from generateconfs.py implementet in containers. i.e migstateclean.

This for general cleanup jobs in MiGrid.

**Comment by jonasbardino** [comment]
It appears the actual `crond` daemon launch was simply missing in the main `migrid` container. Added in latest revision and the cron daemon now does start in that container. Please verify that it solves the issue with missing 2FA session cleanup.
