### ISSUE TITLE
Troubleshooting section is missing in readthedocs

### ISSUE THREAD

**Issue by benibr** [ucphhpc/docker-migrid#48]
The troubleshooting section from the docs https://github.com/ucphhpc/docker-migrid/tree/master/doc/source/sections/troubleshooting is not visible in the readthedocs build: https://docker-migrid.readthedocs.io/en/latest/sections/getting-started/index.html
I'm not sure why, maybe because the section lacks a index.rst?

**Comment by jonasbardino** [comment]
I'm not a ReadTheDocs or Sphinx expert and have a bit too much else to tend to. Maybe something for @SebastianPrehn or @aputto to look into? :-)

**Comment by SebastianPrehn** [comment]
I can look into it Thursday

**Comment by jonasbardino** [comment]
That would be great!
