### ISSUE TITLE
Which cases should be tested in CI?

### ISSUE THREAD

**Issue by benibr** [ucphhpc/docker-migrid#51]
docker-migrid offeres a lot of different container versions which can be used: centos7, rocky8, rocky9 and also 3 different environments (prod, dev, dev_gp). We should decide which combinations of those should be tested in CI.
Testing production configs is probably not possible because is requires further DNS configs.

Please write down which aspects are deprecated or which combinations you use, then I can add them to the CI tests.

**Comment by jonasbardino** [comment]
We still use centos7 in production running without docker on our main sites, ERDA and SIF, and rocky9 in docker on the less used MiGrid site. 
We will migrate our main sites to rocky9 in docker before centos7 has EoL this summer, in line with milestone 1.
We manually test 'production' setups in centos7, rocky8 and rocky9 on development and test instances.

Therefore rocky9 is the only important CI target for us. I actually recently briefly considered adding `development_gdp` to the mix  as that will become increasingly relevant in relation to migrating our sensitive data site, SIF. 
If anybody wants to add it before we find the time you're of course welcome to do so.

**Comment by jonasbardino** [comment]
Yes, I think that's a good start. I did some fixes to get them to build on my laptop in relation to issue #52 so hopefully it'll "just work" in CI, too.

**Comment by benibr** [comment]
Alright, I added #53 to add those extra tests.
