### ISSUE TITLE
Variables section is missing in the readthedocs

### ISSUE THREAD

**Issue by benibr** [ucphhpc/docker-migrid#60]
For some reason the Variables tables is not shown in https://docker-migrid.readthedocs.io/en/latest/sections/configuration/variables.html

**Comment by jonasbardino** [comment]
AFAICT the new `QUOTA_GOCRYPTFS_XRAY` entry in the variables doc is broken. Premature line break.
```
0| ../docker-migrid/doc > make html
Running Sphinx v4.3.2
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 19 source files that are out of date
updating environment: [new config] 19 added, 0 changed, 0 removed
reading sources... [100%] sections/troubleshooting/migrid                                               
[...]/docker-migrid/doc/source/sections/configuration/variables.rst:454: WARNING: Bullet list ends without a blank line; unexpected unindent.
...
```

the new `QUOTA_LUSTRE_BASE,` `QUOTA_GOCRYPTFS_XRAY` and `QUOTA_GOCRYPTFS_SOCK` look unused, btw.

Please have another go at it @Martin-Rehr  and check that it builds on readthedocs after changes.

**Comment by Martin-Rehr** [comment]
Added missing blank newline to doc/source/sections/configuration/variables.rst in commit 5baf87fc9717edf0a2c86b26df965d100ed438b7

QUOTA_LUSTRE_BASE, QUOTA_GOCRYPTFS_XRAY and QUOTA_GOCRYPTFS_SOCK:
==============================================================
The lustre quota container is in it's initial test state and therefore not applied to the docker-compose files of 'docker-migrid' yet. The current test setup can be found in:
https://github.com/ucphhpc/docker-migrid-ucphhpc/blob/main/docker-compose_dev-sif.erda.dk_full.yml
https://github.com/ucphhpc/docker-migrid-ucphhpc/blob/main/advanced_dev2-sif.erda.dk_full.env

Once we deem it "working" it will be applied to the docker-compose files of 'docker-migrid'

**Comment by jonasbardino** [comment]
Alright, the doc build seems to work again now and result in a functional table, so let's close the issue here.

For the record development-only variables should not be included in the docker-migrid `production.env` and therefore by CI requirements in the doc until they are actually functional.
