### ISSUE TITLE
 v1.0.8 not building current stable version of migrid

### ISSUE THREAD

**Issue by esbenvial** [ucphhpc/docker-migrid#62]
Current stable release v1.0.8 not compatible with migrid version v1.11.0.

The following error when building the container image:

From make.log:
#77 0.645 Error:  option --ext_oidc_cookie_same_site not recognized

**Comment by jonasbardino** [comment]
Thanks for testing it with the official release and reporting back @esbenvial . 
Sorry, I missed that incompatibility as I only tested with later github revisions while working on the migrid-sync issue 49 about sign up :-/

We've prepared a new `migrid-sync` stable release, including a fix for that part now. It should also address this issue.
https://github.com/ucphhpc/migrid-sync/releases/tag/v.1.12.0
